version: "3.4"

services:
  backend:
    image: variusgc/smevo-app:latest
    restart: unless-stopped
    command: /smevo/scripts/entrypoint.sh
    volumes:
      - ./static:/smevo/static
      - ./libmachines.so:/smevo/machine_params/libmachines.so
      - ./license.py:/smevo/settings/license.py
    ports:
      - "8000:8000"
    env_file:
      - .smevo.env
    depends_on:
      - db
  worker:
    image: variusgc/smevo-app:latest
    restart: unless-stopped
    command: /smevo/scripts/worker.sh
    volumes:
      - ./static:/smevo/static
      - ./libmachines.so:/smevo/machine_params/libmachines.so
      - ./license.py:/smevo/settings/license.py
    env_file:
      - .smevo.env
    depends_on:
      - backend
      - db
  node:
    env_file:
      - .node.env
    image: variusgc/smevo-node:latest
    restart: always
    ports:
      - "3003:3003"

  db:
    image: postgres:13.6
    restart: always
    env_file:
      - .db.env
    volumes:
      - ${POSTGRESS_DB_VOLUME}:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./smevo-webapp:/smevo
      - ./smevo-nginx/smevo.conf:/etc/nginx/conf.d/default.conf
      - ./static:/smevo/static
    depends_on:
      - backend
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/doker/volumes
      - portainer_data:/data

networks:
  default:
    external: true
    name: smevo

volumes:
  portainer_data:
